<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxpHIMc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxpHIMc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxpHIMc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxpHIMc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMxpHIMc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MxpHIMc',
    'container.build_id' => '9b71d3f0',
    'container.build_time' => 1563982277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxpHIMc');
